### ISSUE TITLE
Document minimum sqlite3 version or use apsw during setup

### ISSUE THREAD

**Issue by DiscordLiz** [unified-moderation-network/salamander#25]
setup.sh uses system sqlite which may be out of date.

**Comment by mikeshardmind** [comment]
Holding on this temporarily. We're probably marking 3.35.2 as the low end

3.35 added support for `returning` which we will likely make use of at some point.

**Comment by mikeshardmind** [comment]
nevermind, added it to the readme with the other deps. This will obviously need to be handled *better* later on, but that can wait until we're ready for a more comprehensive documentaion.
