### ISSUE TITLE
[config.toml] Add non-interactive cli tool to generate config.toml

### ISSUE THREAD

**Issue by mikeshardmind** [unified-moderation-network/salamander#39]
CC: @LGACode 

I'm marking this as planned, but I'm not committing to a design for it yet

**Comment by LGACode** [comment]
Perhaps there can be an alternative "lite" install path that makes a few assumptions and asks for only the most essential info to be able to successfully generate the config

**Comment by mikeshardmind** [comment]
FWIW, currently a lack of `config.toml` already does the "quick" behavior. assumptions are made for 

1. Current working directory as data safe
2. What extensions to include (IIRC, all of them, though subject to change)

**Comment by mikeshardmind** [comment]
alternative handling for this will come in a different form later.
