### ISSUE TITLE
Add Role Support to Bot Admin and Bot Mod

### ISSUE THREAD

**Issue by LGACode** [unified-moderation-network/salamander#42]
As discussed in the Discord, many orgs existing infrastructure/procedures rely on Discord's role system for bot access, rather than direct user assignments. Both methods should be supported to accommodate as many potential users of this system as possible that may be migrating from existing processes.

**Comment by mikeshardmind** [comment]
resolved in 8ccf4a71ddb8a52ba6f099c4b0927a6204ff9bbe

May benefit from further optimizations later, but the exposed interface will allow for that.
