### ISSUE TITLE
Support multiple roles for setadminrole and setmodrole

### ISSUE THREAD

**Issue by LGACode** [unified-moderation-network/salamander#44]
Due to Discord's role structure (as well as other unified comm apps that may be supported in the future), some servers have more than 2 tiers of moderation roles, such as Moderator, Administrator, and Super Admin.

![image](https://user-images.githubusercontent.com/6125912/124551877-032b7000-ddf0-11eb-863a-b5df0d76707e.png)

**Comment by LGACode** [comment]
Related to #45

**Comment by mikeshardmind** [comment]
I don't know that this is an appropriate solution for the problem. I'll need to think about this more, but this feels wrong in a few ways.

- If all of those roles have permission to do things manually, then the bot won't even need to look at if they are a bot mod/bot admin. The permissions the roles are granting will allow access.
- If the roles are being used as tiering and do not directly grant any permissions, then the simple solutions are either add a role that all mods have or make the existing mod roles cumulative on the user. (same for admin) 

Additionally, adding multiple mod/admin roles as a setting encourages things about discord permission layouts which I do not want to encourage.

There are a few types of roles.

- Cosmetic
- Those that grant/deny access via channel settings
- Those that grant server permissions.


Cosmetic ones should always be 0 permissioned and sorted below all non-cosmetic roles.
Access granting/denying roles should be just above those and also be zero permissioned at the server level.
Those that grant permissions (mods and such) should be sorted as a hierarchy.

Assuming such a hierarchy from the discord side (which is definitively the only layout that does not experience any permission hierarchy issues in any setting and which discord optimizes their event dispatch for on the gateway & push notification side) It's safe to add zero [discord] permission roles at the appropriate places (preventing hierarchy based privilege escalation with assigning yourself a role) within the granting permission section which grant bot access.

**Comment by mikeshardmind** [comment]
This is going to be obsolete with slash command permissions anyhow, leaving as-is until that switchover.
