### ISSUE TITLE
Allow Granting/Restricting Cogs and Specific Commands on a Per User or Role Basis

### ISSUE THREAD

**Issue by LGACode** [unified-moderation-network/salamander#45]
To support the new setadminrole and setmodrole commands, there may be certain situations where a specific server utilizing the platform needs to granularly restrict/grant access to certain commands. This is especially true in a MSP environment where the loaded cogs cover a wide audience, and individual servers would want control over that.

**Comment by mikeshardmind** [comment]
Obsoleted by slash command permissions once we switch over.
