### ISSUE TITLE
Target python3.9

### ISSUE THREAD

**Issue by DiscordLiz** [unified-moderation-network/salamander#53]

**Comment by mikeshardmind** [comment]
I could be convinced to make our lower bound python3.9 at this point, but 3.10 is not realistic to consider outside of ensuring future compatibility right now. As of 6d7cce8907b623bdd4da6550faaa80d8ef605eb1 there are wheels available for almost all of our native deps for python 3.9 (the exception being apsw, which we have a bit of a hack of a workaround for to ensure we cache builds of it as wheels)

This doesn't mean we can support windows right now though. There are other issues there with supporting hyperscan setup currently, and scope creep which I'm not interested in considering currently. (apsw however isn't an issue here, there's a windows installer available)

Thoughts on 3.9 being worth the upgrade, or should we wait for 3.10?

**Comment by DiscordLiz** [comment]
3.10 just had it's first release candidate but will not be stabilized until October.
3.9 had many things be deprecated which should be checked against.
3.9 also improves the type annotation situation. I know you have some complaints about how this was done, but being on a version where the builtins are all generic as the lowest supported version at least removes any reason to care about that in this project.

There do not appear to be any must have features in 3.9, but I think it is still worth doing rather than waiting for 3.10 to be ready

**Comment by mikeshardmind** [comment]
This is going to take a few different changes to go over everything I'd want to do with a 3.9 version bump

- [ ] Changes to the event loop handling to use (new in 3.9) `asyncio.shutdown_default_executor`
- [ ] Fewer imports from typing (using builtin generics)
- [ ] Ensure all dependencies work as intended on 3.9 (This appears to be the case at a glance, but has not been verified yet)
- [ ] Ensure no `DependencyWarnings` are being raised with patterns or usages that have been deprecated. 
- [ ] Update various documentation and scripts to use python3.9
