### ISSUE TITLE
check for 3.10 compatability

### ISSUE THREAD

**Issue by DiscordLiz** [unified-moderation-network/salamander#55]
related to #53

**Comment by mikeshardmind** [comment]
We won't be able to jump to 3.11 immediately, and a jump to 3.10 is still wanted (Still blocked on numba+llvmlite's next releases) 

3.11 is a definite improvement once we are able to, but we will need dependencies to support it. Let's discuss that one separately and not skip 3.10

**Comment by DiscordLiz** [comment]
The upgrade to 3.10 is no longer blocked by any dependencies.

**Comment by mikeshardmind** [comment]
> The upgrade to 3.10 is no longer blocked by any dependencies.

Thanks for checking up on that. If you want to go ahead with upgrading, it should be relatively simple to do without conflicting much either now or after the stuff I'll be working on over the weekend.

**Comment by DiscordLiz** [comment]
1772b9e419d522aba91168e6be544f086152ff3e
