### ISSUE TITLE
Consider removing the about command

### ISSUE THREAD

**Issue by mikeshardmind** [unified-moderation-network/salamander#56]
Might not be needed after this:

![image](https://user-images.githubusercontent.com/22035876/125863777-a8a4f5d6-334f-4779-9a03-81da71fc0ccf.png)

(ED: accidentally hitting enter while opening the issue is fun)

**Comment by LGACode** [comment]
Will UMN be able to update that field though? Kinda seems like that's more for the person hosting UMN.

**Comment by mikeshardmind** [comment]
Unclear at this time if it will be editable via bot API. It isn't currently, but may change (discussion in discord-developers server)

Even if it is not, it might just mean moving the non-configurable parts (versions of things used) into an acknowledgments command (related to #41) and still remove the configurable about command. Leaving this here for consideration, but it is not lost on me that we have info in that command currently which should remain dynamically set by the running bot.
