### ISSUE TITLE
Searchban: Add Support to Include/Exclude Users with Roles

### ISSUE THREAD

**Issue by LGACode** [unified-moderation-network/salamander#57]
This flag would be useful in a variety of situations, however the most prominent would be in conjunction with the --no-pfp flag to help limit the scope of that ban further. See below conversation on r/futurism:

![image](https://user-images.githubusercontent.com/6125912/128371210-7ede4a13-48b7-410c-a820-dddd18fd6ce7.png)

**Comment by mikeshardmind** [comment]
There's a similar, but different filter in role management.

I think I'd like to find a good way to merge the logic between these while still only allowing specific filters on specific commands without duplicating any logic. I may add support for this prior to doing that as a short-term handling, but it would be limited to a 1-off to support this relatively basic case if so.

**Comment by mikeshardmind** [comment]
a6e1210c40ee6e75b6bbc2a08636c5bbfceb0bbf
