### ISSUE TITLE
[FR] [MassRole] Add Ability to Cancel a Running Command

### ISSUE THREAD

**Issue by LGACode** [unified-moderation-network/salamander#76]
Sometimes a massrole command will take a very long time depending on the search criteria. It would be useful to be able to interrupt the bot while it's running this.

Instructions on how to cancel should be included in the following bot message: "This may take a while given the number of members to update."

**Comment by mikeshardmind** [comment]
I don't think there's a good way to do this. Interrupting this kind of command part way through would leave roles having been modified on a portion of users. 

Should the bot then go undo all of what it did? (still a ratelimited, and therefore lengthy process) 
Leave the user having to go manually undo it?

Neither of these is a satisfying answer, and I think that it may be more important to address why you'd like to be able to cancel this.

**Comment by LGACode** [comment]
Yes too easy for mods to execute commands without understanding the impact, see #77

**Comment by mikeshardmind** [comment]
Thanks for confirming that, I think I'm going to close this one for now and focus efforts on preventing unintentional misuse of commands for now. This one can be re-opened and re-considered if this remains an issue after those efforts.
