### ISSUE TITLE
[FR] [MassRole] Add Warnings for Large Operations

### ISSUE THREAD

**Issue by LGACode** [unified-moderation-network/salamander#77]
The number of affected users should be presented to the command runner and prompt for confirmation before actually executing, similar to how searchban works.

Additionally, it would be useful to also include an Estimated Run Time at this same time, so the command runner can make a more informed decision on if they want to go through with executing the command or not. I understand operation time estimates can always be tricky, so this is lower priority than showing the number of affected users.

**Comment by mikeshardmind** [comment]
Estimated runtime isn't terrible with this particular operation, but accuracy of this might be a bit rough at first. I can at least offer "this will take at least x time" for now though.

There's a global ratelimit on top of the per route ratelimits, so other things the bot is doing can impact this.

I think we can do a few things to help remedy this. In particular, I've been looking at a way to add priority scheduling of API requests to the bot. Things considered moderation efforts would receive a higher priority than bulk updates like this.

With a centralized scheduling, we'd have a better picture available to calling code of progress there depending on implementation, but any semi-accurate estimation would require this.

**Comment by mikeshardmind** [comment]
As for the confirmation, I'm somewhat hesitant to add too many things which require user confirmation. Users can quickly become desensitized to them, so I'm going to look into ways to make sure we present only relevant confirmations and frontload the most important info from the confirmation in the process. I believe this is worth doing, but that needs to be done well to have such worth.

**Comment by mikeshardmind** [comment]
Not a direct warning, but I believe the interactive approach in #78 will address it being too easy to take actions without understanding the impact, so discussion of that can continue there.
